### ISSUE TITLE
add name setter

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/mindgraph#10]
Implement a pythonic setter on the "name" attribute of a `Node` object. Should make use of mypy's static type checking.

Unit test should look something like:
```
def test_node_name_setter():
    deadliestAdversary = Node()
    deadliestAdversary.name = 'Khan!!!'
    assert deadliestAdversary.name == 'Khan!!!'
```

**Comment by mohit2agrawal** [comment]
Hi!
I would like to help out with this one.

**Comment by capsulecorplab** [comment]
@mohit2agrawal go for it!
