### ISSUE TITLE
Add setter and getter for weighted nodes

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/mindgraph#2]
Nodes should have a positional argument in the constructor, with a pythonic setter & getter, for weights.
If none provided during instantiation, default should be 1.
e.g.,
```
>>> myNode = mg.Node('my node')
>>> myNode.weight
1
>>> myNode.weight = 2
>>> myNode.weight
2
```

Tips: define an internal attribute, self._weight, in the `__init__()` method of the `Node` class. Use the `@property` decorator for the setter and getter. The `weight` attribute should also be of type `int`.

**Comment by solomon-b** [comment]
heres a PR: https://github.com/capsulecorplab/mindgraph/pull/6
:)

**Comment by capsulecorplab** [comment]
Merged!
