### ISSUE TITLE
run as script in bash shell

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/mindgraph#3]
Takes one, or more, yaml file as a command-line argument, then prints graph output for each file. 
e.g.,
```
$ python mindgraph mygraph.yaml
```

Tip: maybe write a `main()` function that performs the following...
```
def main():
    for arg in sys.argv[2:]:
        graph = read_yaml(arg)
        print(graph)
```

**Comment by nk521** [comment]
What do you actually want? Like `python -m mindgraph mygraph.yaml`?
That arg thing should be implemented by the user.

**Comment by capsulecorplab** [comment]
@nk521 this issue is for adding the command line functionality. Using sys.argv was just a suggestion, but if there's a better way to implement that behavior, I'm open to alternatives. I guess it should ideally work with or without the `-m` flag? I haven't quite looked into detail what `-m` does, tbh

**Comment by capsulecorplab** [comment]
If it helps for context, `python -m mindgraph mygraph.yaml` should return the same string as print(graph) in the [example usage](https://github.com/capsulecorplab/mindgraph#example-usage), except we're constructing the `Graph` object from a yaml file instead.

**Comment by sibidass** [comment]
created a PR #15  for adding mindgraph-cli cmd line utility. Also added a method to validate the yaml files to be read. Hope it helps.
