### ISSUE TITLE
make print() and __repr__() return the same string for Graph objects

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/mindgraph#4]
The goal of this change is to allow a user to enter a `Graph` object in a python repl without having to use print().

e.g.,
```
>>> graph = mg.read_yaml('mygraph.yaml') # returns a Graph object
>>> graph # prints string representation of graph object
```

Notes: this seems relevant https://docs.python.org/3.2/library/reprlib.html#reprlib.recursive_repr

**Comment by Abelarm** [comment]
Hi I'd like to work on this!

**Comment by capsulecorplab** [comment]
@Abelarm all yours! :muscle:

**Comment by capsulecorplab** [comment]
#13 Merged!
