### ISSUE TITLE
feature: append() by Node

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/mindgraph#9]
Current implementation only takes string arguments and internally creates and returns a new `Node` object that gets added to its "threads" attribute (list). New implementation should also be able to take a `Node` object itself...

Unit test should look something like
```
def test_node_append_node():
    rootNode = Node('root node')
    subNode = rootNode.append(Node('sub node'))
    assert rootNode[0] is subNode
```

**Comment by RedMoon32** [comment]
I will take this one

**Comment by RedMoon32** [comment]
#11

**Comment by capsulecorplab** [comment]
Nice!
